version: '3.8'

services:
  redis:
    image: redis:alpine

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/main.py:/app/main.py
    depends_on:
      - redis

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
#      - ./frontend/static:/app/static
      - ./frontend:/app
    ports:
      - '8501:8501'
